services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_TYPE=mariadb
      - DB_HOST=nextcloud_db
      - DB_NAME=nextcloud_db
      - DB_USER=nextcloud
      - DB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /docker-data/nextcloud/config:/config
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    networks:
      - nextcloud_network

  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - UMASK_SET=022
    volumes:
      - /docker-data/nextcloud/db:/config
    restart: unless-stopped
    networks:
      - nextcloud_network

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - nextcloud_network
    volumes:
      - /docker-data/nextcloud/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  nextcloud_network:
    driver: bridge
